workInfo:
  title: "Fugue BWV 849"
  fullTitle: "Prelude and Fugue in C-sharp minor, BWV 849"
  composer: "J.S. Bach"
  workId: "bwv849"
  movementName: "Fugue"
  externalURL: "https://en.wikipedia.org/wiki/Prelude_and_Fugue_in_C-sharp_minor,_BWV_849"

files:
  audioPath: "bwv849.mp3"
  
musicalStructure:
  ## totalDurationSeconds: 463.104000 (ffprobe -i exports/bwv849.mp3 -show_entries format=duration -v quiet -of csv="p=0")
  totalDurationSeconds: 209.09
  totalMeasures: 115
  visualLeadTimeSeconds: 0

